a bit better

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -22,7 +22,7 @@ jobs:
     strategy:
       matrix:
         bellsoft_liberica_bp_version: [ "10.7.1", "10.7.2" ]
-        os: [ ubuntu-latest ]
+        os: [ ubuntu-latest, buildjet-8vcpu-ubuntu-2204-arm ]
 
     runs-on: ${{ matrix.os }}
 
@@ -38,8 +38,9 @@ jobs:
           docker run --entrypoint=/layers/paketo-buildpacks_bellsoft-liberica/jre/bin/java test -version
       - name: run image and exit
         timeout-minutes: 1
-        continue-on-error: true
         run: |
-          docker run --env JAVA_TOOL_OPTIONS="-Xlog:cds -XX:+PrintFlagsFinal" test 2>&1 | tee output.txt
+          timeout 10s docker run -it test 2>&1 | tee output.txt; test $? -eq 143 && echo "Container ran for 10 seconds without failing"
+          cat output.txt
           # if "Dynamic archive cannot be used" is found in the logs, it means CDS did not apply; exit with error
+          echo "Testing for the presence of 'Dynamic archive cannot be used'; failing the build if we find it "
           cat output.txt | grep "Dynamic archive cannot be used" -vqz
